name: Build Pikachu

trigger:
- main


variables:
  - name: AZURE_WEBAPP_NAME
    value: pikachu-dev
  - name: AZURE_WEBAPP_PACKAGE_PATH
    value: 'src\Kooco.Pikachu.Blazor\published'
  - name: CONFIGURATION
    value: Release
  - name: DOTNET_CORE_VERSION
    value: '8.x'
  - name: WORKING_DIRECTORY
    value: 'src\Kooco.Pikachu.Blazor'
  - name: AZURE_WEBAPP_NAME_PRODUCTION
    value: 'pikachu-production'


jobs:
- job: build
  #pool:
    #name: KOOCO Build Agent
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      includePreviewVersions: false
      version: ${{ variables.DOTNET_CORE_VERSION }}
      
  - script: dotnet restore "${{ variables.WORKING_DIRECTORY }}"
    displayName: 'Restore'

  - script: dotnet build "${{ variables.WORKING_DIRECTORY }}" --configuration ${{ variables.CONFIGURATION }} --no-restore 
    displayName: 'Build'


  - script: dotnet test "${{ variables.WORKING_DIRECTORY }}" --no-build
    displayName: 'Test'

    
  - script: dotnet publish "${{ variables.WORKING_DIRECTORY }}" --configuration ${{ variables.CONFIGURATION }} --no-build --output "${{ variables.AZURE_WEBAPP_PACKAGE_PATH }}"
    displayName: 'Publish'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '${{ variables.AZURE_WEBAPP_PACKAGE_PATH }}'
      artifactName: 'webapp'

